### ISSUE TITLE
Files in the utilis dont work

### ISSUE THREAD

**Issue by jamila-griffith** [TheJacksonLaboratory/phenix-service#1]
Hi,

I am trying to extract the metadata from the 3 files you have in the utilis but none of them worked. I get this error

Unrecognized arguments: -f

Can you please help.

**Comment by wflynny** [comment]
Hi @jamila-griffith, can you please show the exact command you are running and the traceback/error text?

**Comment by jamila-griffith** [comment]
Hi,

I have run the harmony_to_tiff.py in jupyter notebook. I have changed the directory to where my archived files are. Then ran this command.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "C:\Users\s2915950\Anaconda3\lib\argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\Users\s2915950\Anaconda3\lib\argparse.py", line 2009, in _parse_known_args
    stop_index = consume_positionals(start_index)
  File "C:\Users\s2915950\Anaconda3\lib\argparse.py", line 1965, in consume_positionals
    take_action(action, args)
  File "C:\Users\s2915950\Anaconda3\lib\argparse.py", line 1858, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "C:\Users\s2915950\Anaconda3\lib\argparse.py", line 2399, in _get_values
    self._check_value(action, value[0])
  File "C:\Users\s2915950\Anaconda3\lib\argparse.py", line 2446, in _check_value
    raise ArgumentError(action, msg % args)
argparse.ArgumentError: argument command: invalid choice: 'C:\\Users\\s2915950\\AppData\\Roaming\\jupyter\\runtime\\kernel-f5833ee8-67d6-4aaa-979e-5824ed6443fb.json' (choose from 'convert', 'metadata', 'list')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\s2915950\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-62-beb5fa2bdab6>", line 12, in <module>
    main()
  File "<ipython-input-62-beb5fa2bdab6>", line 3, in main
    args = argparser.parse_args()
  File "C:\Users\s2915950\Anaconda3\lib\argparse.py", line 1768, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "C:\Users\s2915950\Anaconda3\lib\argparse.py", line 1807, in parse_known_args
    self.error(str(err))
  File "C:\Users\s2915950\Anaconda3\lib\argparse.py", line 2521, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "C:\Users\s2915950\Anaconda3\lib\argparse.py", line 2508, in exit
    _sys.exit(status)
SystemExit: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\s2915950\Anaconda3\lib\site-packages\IPython\core\ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "C:\Users\s2915950\Anaconda3\lib\site-packages\IPython\core\ultratb.py", line 248, in wrapped
    return f(*args, **kwargs)
  File "C:\Users\s2915950\Anaconda3\lib\site-packages\IPython\core\ultratb.py", line 281, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "C:\Users\s2915950\Anaconda3\lib\inspect.py", line 1515, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
AttributeError: 'tuple' object has no attribute 'tb_frame'
INFO:root:
Unfortunately, your original traceback can not be constructed.

usage: ipykernel_launcher.py [-h] {convert,metadata,list} ...
ipykernel_launcher.py: error: argument command: invalid choice: 'C:\\Users\\s2915950\\AppData\\Roaming\\jupyter\\runtime\\kernel-f5833ee8-67d6-4aaa-979e-5824ed6443fb.json' (choose from 'convert', 'metadata', 'list')
---------------------------------------------------------------------------
ArgumentError                             Traceback (most recent call last)
~\Anaconda3\lib\argparse.py in parse_known_args(self, args, namespace)
   1799         try:
-> 1800             namespace, args = self._parse_known_args(args, namespace)
   1801             if hasattr(namespace, _UNRECOGNIZED_ARGS_ATTR):

~\Anaconda3\lib\argparse.py in _parse_known_args(self, arg_strings, namespace)
   2008         # consume any positionals following the last Optional
-> 2009         stop_index = consume_positionals(start_index)
   2010 

~\Anaconda3\lib\argparse.py in consume_positionals(start_index)
   1964                 start_index += arg_count
-> 1965                 take_action(action, args)
   1966 

~\Anaconda3\lib\argparse.py in take_action(action, argument_strings, option_string)
   1857             seen_actions.add(action)
-> 1858             argument_values = self._get_values(action, argument_strings)
   1859 

~\Anaconda3\lib\argparse.py in _get_values(self, action, arg_strings)
   2398             value = [self._get_value(action, v) for v in arg_strings]
-> 2399             self._check_value(action, value[0])
   2400 

~\Anaconda3\lib\argparse.py in _check_value(self, action, value)
   2445             msg = _('invalid choice: %(value)r (choose from %(choices)s)')
-> 2446             raise ArgumentError(action, msg % args)
   2447 

ArgumentError: argument command: invalid choice: 'C:\\Users\\s2915950\\AppData\\Roaming\\jupyter\\runtime\\kernel-f5833ee8-67d6-4aaa-979e-5824ed6443fb.json' (choose from 'convert', 'metadata', 'list')

During handling of the above exception, another exception occurred:

SystemExit                                Traceback (most recent call last)
    [... skipping hidden 1 frame]

<ipython-input-62-beb5fa2bdab6> in <module>
     11 if __name__ == "__main__":
---> 12     main()

<ipython-input-62-beb5fa2bdab6> in main()
      2     argparser = construct_argparser()
----> 3     args = argparser.parse_args()
      4 

~\Anaconda3\lib\argparse.py in parse_args(self, args, namespace)
   1767     def parse_args(self, args=None, namespace=None):
-> 1768         args, argv = self.parse_known_args(args, namespace)
   1769         if argv:

~\Anaconda3\lib\argparse.py in parse_known_args(self, args, namespace)
   1806             err = _sys.exc_info()[1]
-> 1807             self.error(str(err))
   1808 

~\Anaconda3\lib\argparse.py in error(self, message)
   2520         args = {'prog': self.prog, 'message': message}
-> 2521         self.exit(2, _('%(prog)s: error: %(message)s\n') % args)

~\Anaconda3\lib\argparse.py in exit(self, status, message)
   2507             self._print_message(message, _sys.stderr)
-> 2508         _sys.exit(status)
   2509 

SystemExit: 2

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
    [... skipping hidden 1 frame]

~\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py in showtraceback(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)
   2052                     stb = ['An exception has occurred, use %tb to see '
   2053                            'the full traceback.\n']
-> 2054                     stb.extend(self.InteractiveTB.get_exception_only(etype,
   2055                                                                      value))
   2056                 else:

~\Anaconda3\lib\site-packages\IPython\core\ultratb.py in get_exception_only(self, etype, value)
    752         value : exception value
    753         """
--> 754         return ListTB.structured_traceback(self, etype, value)
    755 
    756     def show_exception_only(self, etype, evalue):

~\Anaconda3\lib\site-packages\IPython\core\ultratb.py in structured_traceback(self, etype, evalue, etb, tb_offset, context)
    627             chained_exceptions_tb_offset = 0
    628             out_list = (
--> 629                 self.structured_traceback(
    630                     etype, evalue, (etb, chained_exc_ids),
    631                     chained_exceptions_tb_offset, context)

~\Anaconda3\lib\site-packages\IPython\core\ultratb.py in structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1365         else:
   1366             self.tb = tb
-> 1367         return FormattedTB.structured_traceback(
   1368             self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1369 

~\Anaconda3\lib\site-packages\IPython\core\ultratb.py in structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1265         if mode in self.verbose_modes:
   1266             # Verbose modes need a full traceback
-> 1267             return VerboseTB.structured_traceback(
   1268                 self, etype, value, tb, tb_offset, number_of_lines_of_context
   1269             )

~\Anaconda3\lib\site-packages\IPython\core\ultratb.py in structured_traceback(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)
   1122         """Return a nice text document describing the traceback."""
   1123 
-> 1124         formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
   1125                                                                tb_offset)
   1126 

~\Anaconda3\lib\site-packages\IPython\core\ultratb.py in format_exception_as_a_whole(self, etype, evalue, etb, number_of_lines_of_context, tb_offset)
   1080 
   1081 
-> 1082         last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)
   1083 
   1084         frames = self.format_records(records, last_unique, recursion_repeat)

~\Anaconda3\lib\site-packages\IPython\core\ultratb.py in find_recursion(etype, value, records)
    380     # first frame (from in to out) that looks different.
    381     if not is_recursion_error(etype, value, records):
--> 382         return len(records), 0
    383 
    384     # Select filename, lineno, func_name to track frames with

TypeError: object of type 'NoneType' has no len()

**Comment by wflynny** [comment]
Hi @jamila-griffith,

`harmony_to_tiff.py` is intended to be a commandline tool.  You can either use IPython/Jupyter magic to do something like:
```
In [1]: import sys

In [2]: {sys.executable} /path/to/harmony_to_tiff.py convert ...
```

or you can import the relevant class from the file:
```
import sys
from pathlib import Path

sys.path.append("/path/to/utils/")
from harmony_to_tiff import HarmonyArchive

archive_location = Path("/where/your/files/are")
output_location = Path("/where/you/want/your/output")

archive = HarmonyArchive(archive_location)
archive.load_image_database()
archive.convert_to_human_readable(output_location)
```

or you can just use the CLI and not Jupyter.

**Comment by jamila-griffith** [comment]
Hi,

Thanks for your response. I am new to python and therefore could not understand what was causing the issue. I appreciate if you can bear with this. I have few questions:

1. What is the exact folder you input for this script. Is this the IMAGES folder which has the sqlite file or just the Harmony-Archive which is the main folder and has the IMAGES and XML folders?

2. Is the script changing the names of the tiff files so that its more readable or giving the metadata also? I think your other scripts (extract metadata from archive and the other one) can probably do that.

My problem is that I have archived all the data from Harmony and the naming of the tiff files does not make any sense to me. Now I want to use the cellprofiler to analyze these images. I know with Export from Harmony its more readable and you can use the regular expression to extract the metadata information. 

Thanks heaps for your help.

**Comment by jamila-griffith** [comment]
Hi,

I have got this working now in IPython. Thanks for your help. 

Could you help with the extract_metadata_from_archive.py

Thanks

**Comment by wflynny** [comment]
Glad you were able to get this working.

The `extract_metadata_from_archive.py` is not nearly as polished.  You would need to do something like:
```
In [1]: import sys

In [2]: {sys.executable} /path/to/extract_metadata_from_archive.py harmony_archive ...
```

**Comment by jamila-griffith** [comment]
This piece of code is for IPython or Jupyter ? 

For the harmony_to_tiff.py I have gone through the following steps in IPython. 

import sys
from pathlib import Path

sys.path.append("C:/Research/")#path where my harmony_to_tiff is
from harmony_to_tiff import HarmonyArchive

archive_location = Path("C:/Users/Harmony-Archive/")
output_location = Path("C:/Users/Output/")

archive = HarmonyArchive(archive_location)
archive.load_image_database()
archive.convert_to_human_readable(output_location)

How do I implement this in IPython? Sorry I am very naive in programming so please dont mind if I ask any stupid question.

Thanks

**Comment by wflynny** [comment]
@jamila-griffith,  both Jupyter and IPython work the same way.  The code you shared above for `harmony_to_tiff` would work in either. 

For getting `extract_metadata_from_archive.py`, you can do:
```
import sys
script_location = "C:/Users/Research/extract_metadata_from_archive.py"
archive_location = Path("C:/Users/Harmony-Archive")
! {sys.executable} {script_location} {archive_location}
```
in Jupyter or IPython.

**Comment by jamila-griffith** [comment]
Thanks again @wflynny. That worked. 

Just a last question: the xmltodict.py converts xml metadata to a dictionary but there are some options as to parse and unparse. The code looks more complicated than the other two but its a cool script to convert the xml to dictionary which can later be imported with the data in Omero. 

Would is be possible to give a step by step guide for this script? Sorry if I am asking too much.

Thanks

**Comment by wflynny** [comment]
Xmltodict is it's own (well documented) repo which you can find [here](https://github.com/martinblech/xmltodict). I only included it as a standalone file here because these scripts have often been needed in weird environments without external internet access for pip/conda.

I would browse around that repo and/or ask for help there. There's likely a much more up to date version as well.

Lastly, if you are working with data generated from an Opera Phenix or Operetta, you are way better off directly using the `Export Data` functionality in Harmony than using these scripts. Since you have the Harmony Archives, you can read the Archives back into Harmony and then Export them. That will ensure the resulting tiffs are bioformats compatible. We've had success directly importing screens in that format to OMERO.

Cheers.
